# Generated by Django 2.2.5 on 2019-09-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190915_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='user',
            new_name='students',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='user',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='user',
            new_name='students',
        ),
    ]
