# Generated by Django 2.2.5 on 2019-09-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190915_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
