# Generated by Django 2.2.5 on 2019-09-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_mark_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='subject',
        ),
    ]
