# Generated by Django 2.2.5 on 2019-09-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190915_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='weighting',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
