# Generated by Django 2.2.5 on 2019-09-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='has_happened',
            field=models.BooleanField(null=True),
        ),
    ]
