# Generated by Django 2.2.5 on 2019-09-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_test_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='people',
            field=models.IntegerField(null=True),
        ),
    ]
