# Generated by Django 2.2.5 on 2019-09-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_class_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
