# Generated by Django 2.2.5 on 2019-11-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_class_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='atar_bonus',
            field=models.BooleanField(null=True),
        ),
    ]
