# Generated by Django 2.2.5 on 2019-11-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_subject_atar_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='atar_bonus',
            new_name='gives_atar_bonus',
        ),
    ]
